include: package:flutter_lints/flutter.yaml

linter:
  rules:
    cancel_subscriptions: true
    avoid_void_async: true
    await_only_futures: true
    avoid_slow_async_io: true
    camel_case_types: true
    empty_constructor_bodies: true
    empty_statements: true
    implementation_imports: true
    prefer_const_constructors: true
    prefer_contains: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_rethrow_when_possible: true
    
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
