default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
    load_asc_api_token
  end

  desc "Load the App Store Connect API token"
  lane :load_asc_api_token do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_P8"],
      is_key_content_base64: true,
      in_house: false
    )
  end

  def bump_build_number()
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
    latest_build_number = latest_testflight_build_number(
      api_key: api_key,
      initial_build_number: 0,
      app_identifier: "com.banthu.bnth.dev"
    )
    return (latest_build_number + 1)
  end
  
  def get_version_name()
    version_name = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]
    
    if version_name.empty?
      puts "*** Version name is empty, using default version name 1.0.0 ***"
      version_name = "1.0.0"
    end
    
    return version_name
  end

  desc "Release a new build to TestFlight"
  lane :release_beta do
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

    sync_code_signing(
      api_key: api_key,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      type: "appstore",
      readonly: true
    )
    
    build_number = bump_build_number()
    version_name = get_version_name()

    puts "*** Build iOS app for development ***"
    Dir.chdir "../.." do
      sh("flutter", "build", "ipa", "--flavor", "development", "--release", "--build-number=#{build_number}", "--build-name=#{version_name}")
    end
    
    puts "*** Archive and sign iOS app ***"
    build_app(
      scheme: "development",
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive"
    )

    puts "*** Upload the app to TestFlight ***"
    upload_to_testflight(
      api_key: api_key,
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end
